function rates = reaction_rates(species, T, kinetics, op, props, p)
    % REACTION_RATES.M
    % Calculates reaction rates R1 to R23 based on species concentrations,
    % temperature, and kinetic parameters. Also integrates peroxide
    % generation from gas crossover physics when the full 6-argument
    % calling convention is used. No ODEs are solved in this file.
    %
    % Two calling conventions are supported:
    %   rates = reaction_rates(species, T, kinetics, op)
    %       "Simplified/mechanism-isolation" mode. species.H2O2 is treated
    %       as a prescribed boundary condition (set by the caller) rather
    %       than dynamically generated by crossover. Used by
    %       species_evolution.m, time_scale_analysis.m and similar
    %       diagnostic scripts that hold H2O2 fixed to isolate Fenton /
    %       attack / unzipping dynamics. rates.S_H2O2 = 0 in this mode
    %       (no crossover source term) and Pt kinetics are skipped unless
    %       species.Pt/species.Pt2 are present.
    %   rates = reaction_rates(species, T, kinetics, op, props, p)
    %       "Full/coupled" mode used by ode_system.m and
    %       lifetime_simulation.m. H2O2 crossover generation is computed via
    %       peroxide_generation.m + hydrogen_crossover.m, and Pt
    %       dissolution/redeposition kinetics are computed via
    %       pt_dissolution.m when species.Pt/species.Pt2 are present.

    R_gas = 8.314462618; % Gas constant (J/mol/K)
    full_mode = (nargin >= 6);

    %% 1. Peroxide Generation from Gas Crossover (full mode only)
    if full_mode
        rates.S_H2O2 = peroxide_generation(species, props, op, p);
    else
        rates.S_H2O2 = 0; % H2O2 treated as a prescribed boundary condition
    end

    %% 2. Calculate Arrhenius Rate Constants (k1 - k23)
    k1  = kinetics.R1.A  * exp(-kinetics.R1.Ea / (R_gas * T));
    k2  = kinetics.R2.A  * exp(-kinetics.R2.Ea / (R_gas * T));
    k3  = kinetics.R3.A  * exp(-kinetics.R3.Ea / (R_gas * T));
    k4  = kinetics.R4.A  * exp(-kinetics.R4.Ea / (R_gas * T));
    k5  = kinetics.R5.A  * exp(-kinetics.R5.Ea / (R_gas * T));
    k6  = kinetics.R6.A  * exp(-kinetics.R6.Ea / (R_gas * T));
    k7  = kinetics.R7.A  * exp(-kinetics.R7.Ea / (R_gas * T));
    k8  = kinetics.R8.A  * exp(-kinetics.R8.Ea / (R_gas * T));
    k9  = kinetics.R9.A  * exp(-kinetics.R9.Ea / (R_gas * T));
    k10 = kinetics.R10.A * exp(-kinetics.R10.Ea / (R_gas * T));
    k11 = kinetics.R11.A * exp(-kinetics.R11.Ea / (R_gas * T));
    k12 = kinetics.R12.A * exp(-kinetics.R12.Ea / (R_gas * T));
    k13 = kinetics.R13.A * exp(-kinetics.R13.Ea / (R_gas * T));
    k14 = kinetics.R14.A * exp(-kinetics.R14.Ea / (R_gas * T));
    k15 = kinetics.R15.A * exp(-kinetics.R15.Ea / (R_gas * T));
    k16 = kinetics.R16.A * exp(-kinetics.R16.Ea / (R_gas * T));
    k17_23 = kinetics.R17_23.A * exp(-kinetics.R17_23.Ea / (R_gas * T));

    %% 2b. Quasi-Steady-State Approximation for fast radicals (full mode only)
    % PHYSICAL/NUMERICAL RATIONALE: OH, OOH and H are produced and consumed
    % by pseudo-first/second-order reactions with rate constants that are
    % many orders of magnitude faster (intrinsic radical lifetime ~ns-us)
    % than the hour-scale macro-timestep used for the slow degradation
    % species. Treating OH/OOH/H as explicit differential ODE states in the
    % same system as the slow species produces a numerically intractable
    % stiffness ratio (>1e12) that standard BDF solvers cannot resolve at
    % this timescale. The quasi-steady-state approximation - treating fast
    % intermediates as instantaneously equilibrated with the slow species -
    % is the standard, literature-established method for handling exactly
    % this situation in radical-chemistry kinetics modeling (see e.g.
    % Turanyi & Tomlin, "Analysis of Kinetic Reaction Mechanisms",
    % Springer, 2014, Ch. 6; and its long-standing use in atmospheric/
    % combustion radical-chemistry modeling). It does NOT change the
    % reaction network or rate constants from Fruhwirt et al. (2020) - it
    % only changes how the fast radical concentrations are numerically
    % obtained (algebraic balance instead of explicit time integration).
    if full_mode
        cf2_sum = species.CF2_7 + species.CF2_6 + species.CF2_5 + species.CF2_4 ...
                + species.CF2_3 + species.CF2_2 + species.CF2_1;
        [OH_qss, OOH_qss, H_qss] = local_radical_qss( ...
            species.Fe2, species.Fe3, species.H2O2, species.SC_SO3H, ...
            species.SC_O, species.BB_O, cf2_sum, op.H2, op.O2, ...
            k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,k11,k12,k13,k14,k15,k16,k17_23);
        species.OH  = OH_qss;
        species.OOH = OOH_qss;
        species.H   = H_qss;
        rates.OH_qss  = OH_qss;
        rates.OOH_qss = OOH_qss;
        rates.H_qss   = H_qss;
    end

    %% 3. Calculate Reaction Rates (R1 to R23)

    % Iron Reactions (R1 - R5)
    rates.R1  = k1 * species.Fe2 * species.H2O2;
    rates.R2  = k2 * species.Fe3 * species.H2O2;
    rates.R3  = k3 * species.Fe2 * species.OH;
    rates.R4  = k4 * species.Fe2 * species.OOH;
    rates.R5  = k5 * species.Fe3 * species.OOH;

    % H2O2 Decomposition (R6)
    rates.R6  = k6 * species.H2O2;

    % Radical Reactions (R7 - R13)
    rates.R7  = k7 * species.OH * species.H2O2;
    rates.R8  = k8 * species.OOH * species.H2O2;
    rates.R9  = k9 * (species.OOH)^2;
    rates.R10 = k10 * (species.OH)^2;
    rates.R11 = k11 * species.OOH * species.OH;
    rates.R12 = k12 * species.OH * op.H2;
    rates.R13 = k13 * species.H * op.O2;

    % Membrane Degradation - Side-chain and Backbone Cleavage (R14 - R16)
    rates.R14 = k14 * species.SC_SO3H * species.OH;
    rates.R15 = k15 * species.SC_O * species.OH;
    rates.R16 = k16 * species.BB_O * species.OH;

    % Backbone Unzipping Sequence (R17 - R23, n = 7 down to 1)
    rates.R17 = k17_23 * species.CF2_7 * species.OH;
    rates.R18 = k17_23 * species.CF2_6 * species.OH;
    rates.R19 = k17_23 * species.CF2_5 * species.OH;
    rates.R20 = k17_23 * species.CF2_4 * species.OH;
    rates.R21 = k17_23 * species.CF2_3 * species.OH;
    rates.R22 = k17_23 * species.CF2_2 * species.OH;
    rates.R23 = k17_23 * species.CF2_1 * species.OH;

    %% 4. Fenton Chemistry Aggregation (R1 - R5) & Propagation (R8 - R13)
    rates.fenton.Fe2 = -rates.R1 + rates.R2 - rates.R3 - rates.R4 + rates.R5;
    rates.fenton.Fe3 =  rates.R1 - rates.R2 + rates.R3 + rates.R4 - rates.R5;

    rates.radicals.OH  =  rates.R1 + 2*rates.R6 - rates.R3 - rates.R7 + rates.R8 ...
                         - 2*rates.R10 - rates.R11 - rates.R12;
    rates.radicals.OOH =  rates.R2 - rates.R4 - rates.R5 + rates.R7 - rates.R8 ...
                         - 2*rates.R9 - rates.R11 + rates.R13;
    rates.radicals.H   =  rates.R12 - rates.R13;

    %% 5. Membrane Attack Rates (R14 - R16)
    rates.attack.side_chain = rates.R14 + rates.R15;
    rates.attack.backbone   = rates.R16;
    rates.attack.total      = rates.R14 + rates.R15 + rates.R16;

    %% 6. Backbone Unzipping Aggregation (R17 - R23)
    rates.unzip.total = rates.R17 + rates.R18 + rates.R19 + rates.R20 + ...
                        rates.R21 + rates.R22 + rates.R23;
    rates.unzip.sequence = [rates.R17, rates.R18, rates.R19, rates.R20, ...
                            rates.R21, rates.R22, rates.R23];

    %% 7. Pt Kinetics (only if Pt species are tracked by the caller)
    % Delegated entirely to pt_dissolution.m (single source of truth -
    % avoids duplicating the Butler-Volmer dissolution/redeposition
    % formulas in two places).
    if isfield(species, 'Pt') && isfield(species, 'Pt2') && isfield(kinetics, 'Pt')
        rates.Pt = pt_dissolution(species, kinetics, p, op);
    end
end

%% ------------------------------------------------------------------
function [OH, OOH, H] = local_radical_qss(Fe2, Fe3, H2O2, SC_SO3H, SC_O, BB_O, ...
        cf2_sum, H2, O2, k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,k11,k12,k13,k14,k15,k16,k1723)
    % Solves the algebraic steady-state balance for OH, OOH, H given the
    % current (slowly-varying) concentrations of Fe2, Fe3, H2O2, and
    % membrane species.
    %
    % IMPLEMENTATION NOTE: this is deliberately a single deterministic pass
    % (no iterative fixed-point loop). An earlier version used damped
    % Picard iteration to fully couple the OH/OOH quadratics, which is more
    % accurate but introduces a non-smooth dependence of the converged
    % answer on the number of iterations taken - this made the stiff
    % solver's finite-difference Jacobian estimate noisy/inconsistent and
    % caused corrector/error-test failures even at vanishingly small step
    % sizes. The sequential single-pass approximation below is exactly
    % reproducible and smooth in its inputs (a fixed sequence of algebraic
    % operations), which is essential for a stiff BDF solver's Newton
    % iteration to converge. The approximation (OH solved first assuming
    % the OOH cross-term k11*OH*OOH is evaluated using OOH from the
    % previous macro-step's converged value, then OOH solved using the new
    % OH) is standard practice for weakly-coupled QSSA radical pairs and
    % introduces negligible error here because k11's contribution to the OH
    % balance is small relative to the dominant SC_SO3H/BB_O/CF2 sink terms.
    %
    % Balance equations (production = consumption):
    %   OH:  R1 + 2*R6 + R8            = R3 + R7 + 2*R10 + R11 + R12
    %                                     + R14 + 3*R15 + R16 + 2*sum(R17-23)
    %   OOH: R2 + R7 + R13              = R4 + R5 + R8 + 2*R9 + R11
    %   H:   R12                        = R13

    eps_ = 1e-30;

    % --- Step 1: OH quadratic, using OOH ~ 0 as a first-pass estimate for
    % the small k8/k11 cross-terms (dominant balance is Fe/H2O2 production
    % vs. SC_SO3H/BB_O/CF2 consumption, so this is a good approximation).
    a_oh = 2*k10;
    b_oh = k3*Fe2 + k7*H2O2 + k12*H2 + k14*SC_SO3H + 3*k15*SC_O + k16*BB_O + 2*k1723*cf2_sum;
    c_oh = k1*Fe2*H2O2 + 2*k6*H2O2;
    OH = local_quad_positive_root(a_oh, b_oh, c_oh);

    % --- Step 2: OOH quadratic, using the OH just solved ---
    a_ooh = 2*k9;
    b_ooh = k4*Fe2 + k5*Fe3 + k8*H2O2 + k11*OH;
    c_ooh = k2*Fe3*H2O2 + k7*OH*H2O2;
    OOH = local_quad_positive_root(a_ooh, b_ooh, c_ooh);

    % --- Step 3: refine OH once more with the OOH cross-terms included ---
    b_oh2 = b_oh + k11*OOH;
    c_oh2 = c_oh + k8*OOH*H2O2;
    OH = local_quad_positive_root(a_oh, b_oh2, c_oh2);

    % --- Step 4: H (linear given OH) ---
    H = (k12 * OH * H2) / max(k13 * O2, eps_);

    OH  = max(OH, 0);
    OOH = max(OOH, 0);
    H   = max(H, 0);
end

%% ------------------------------------------------------------------
function x = local_quad_positive_root(a, b, c)
    % Solves a*x^2 + b*x - c = 0 for the non-negative root (c >= 0
    % physically, since it is a sum of production rates).
    %
    % FIX (critical bug): the naive formula x = (-b + sqrt(b^2+4ac)) / (2a)
    % suffers CATASTROPHIC CANCELLATION whenever b^2 >> 4ac (the common
    % case here: b is dominated by a large linear sink term, e.g.
    % k14*SC_SO3H ~ 1e9, while c - the production term - is often many
    % orders of magnitude smaller). In that regime, sqrt(b^2+4ac) rounds to
    % exactly b in double precision, so -b+sqrt(...) evaluates to EXACTLY
    % ZERO, silently killing the entire reaction network (this was
    % observed to freeze all membrane-attack/unzipping chemistry after the
    % first simulated hour). The numerically stable "Citardauq" form below
    % (x = 2c / (b + sqrt(b^2+4ac))) avoids subtracting two nearly-equal
    % large numbers and remains accurate across the full range of a, b, c
    % encountered in this project.
    if a < 1e-30 && b < 1e-30
        x = 0;
        return;
    end
    disc = b^2 + 4*a*c;
    x = (2*c) / (b + sqrt(max(disc, 0)));
    x = max(x, 0);
end
